<a href="https://colab.research.google.com/github/tao73bot/PythonLearing-BS/blob/main/L10_NumPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([1,2,3,4,4,5,])
a

array([1, 2, 3, 4, 4, 5])

In [2]:
a[0]

1

In [3]:
type(a)

numpy.ndarray

In [4]:
a+1

array([2, 3, 4, 5, 5, 6])

## 2D array

In [5]:
a2D = np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
a2D

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
a2D[1] + 1

array([5, 6, 7])

In [10]:
# .size() --> number of all element
print(a.size)
print(a.shape)
print(a2D.size)
print(a2D.shape)

6
(6,)
9
(3, 3)


In [12]:
# dimension
a.ndim

1

In [13]:
a2D.ndim

2

### array Data type

In [14]:
a2D.dtype

dtype('int64')

In [17]:
b2D = np.array([
    [1,2,3],
    [4,'u',6],
    [7,8,9]
])
print(b2D)
b2D.dtype

[['1' '2' '3']
 ['4' 'u' '6']
 ['7' '8' '9']]


dtype('<U21')

In [18]:
# if data inside is convertable then numpy will convert it auto if define datatype
c2D = np.array([
    [1,2,3],
    [4,'5',6],
    [7,8,'9']
],dtype=np.int64)
c2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Creation Method

In [20]:
np.full((2,),3)

array([3, 3])

In [21]:
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [22]:
np.full((3,3,3,),4)

array([[[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]])

In [24]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [27]:
np.linspace(10,100,15) # it will select 15 number with same difference

array([ 10.        ,  16.42857143,  22.85714286,  29.28571429,
        35.71428571,  42.14285714,  48.57142857,  55.        ,
        61.42857143,  67.85714286,  74.28571429,  80.71428571,
        87.14285714,  93.57142857, 100.        ])

## numpy operation

In [28]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)

In [29]:
(a1+5)

array([ 6,  7,  8,  9, 10])

In [30]:
(a1*a2)

array([ 6, 14, 24, 36, 50])

In [31]:
(a1+a2)*10

array([ 70,  90, 110, 130, 150])

In [32]:
a1_new = np.array([1,2,3])
a2_new = np.array([[1],[2]])

(a1_new + a2_new)

array([[2, 3, 4],
       [3, 4, 5]])