<a href="https://colab.research.google.com/github/tao73bot/PythonLearing-BS/blob/main/L10_NumPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1,2,3,4,4,5,])
a

array([1, 2, 3, 4, 4, 5])

In [ ]:
a[0]

1

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a+1

array([2, 3, 4, 5, 5, 6])

## 2D array

In [ ]:
a2D = np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
a2D

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
a2D[1] + 1

array([5, 6, 7])

In [ ]:
# .size() --> number of all element
print(a.size)
print(a.shape)
print(a2D.size)
print(a2D.shape)

6
(6,)
9
(3, 3)


In [ ]:
# dimension
a.ndim

1

In [ ]:
a2D.ndim

2

### array Data type

In [ ]:
a2D.dtype

dtype('int64')

In [ ]:
b2D = np.array([
    [1,2,3],
    [4,'u',6],
    [7,8,9]
])
print(b2D)
b2D.dtype

[['1' '2' '3']
 ['4' 'u' '6']
 ['7' '8' '9']]


dtype('<U21')

In [ ]:
# if data inside is convertable then numpy will convert it auto if define datatype
c2D = np.array([
    [1,2,3],
    [4,'5',6],
    [7,8,'9']
],dtype=np.int64)
c2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Creation Method

In [ ]:
np.full((2,),3)

array([3, 3])

In [ ]:
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
np.full((3,3,3,),4)

array([[[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
np.linspace(10,100,15) # it will select 15 number with same difference

array([ 10.        ,  16.42857143,  22.85714286,  29.28571429,
        35.71428571,  42.14285714,  48.57142857,  55.        ,
        61.42857143,  67.85714286,  74.28571429,  80.71428571,
        87.14285714,  93.57142857, 100.        ])

## numpy operation

In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)

In [ ]:
(a1+5)

array([ 6,  7,  8,  9, 10])

In [ ]:
(a1*a2)

array([ 6, 14, 24, 36, 50])

In [ ]:
(a1+a2)*10

array([ 70,  90, 110, 130, 150])

In [ ]:
a1_new = np.array([1,2,3])
a2_new = np.array([[1],[2]])

(a1_new + a2_new)

array([[2, 3, 4],
       [3, 4, 5]])

## Indexing and Slicing NumPy array

### Part1 - Basic Indexing

In [1]:
import numpy as np


In [2]:
exam_scores = np.array([90,83,84,75,98])
print("First scores is: ", exam_scores[0])

First scores is:  90


### Part2 - MultiDimentional Indexing

- Accessing element in 2D and 3D array
- Using row and coloumm index

In [3]:
sales_data = np.array([
    [2,3,4],
    [4,5,6],
    [6,7,8]
])
# we access using a[row][column] or a[row,column]
# print mid element
print(sales_data[1][1])
print(sales_data[1,1])

5
5


### Part3 - Basic Slicing
        - How to slice array to set sub-array
        - using the `start:stop:step` notation

In [5]:
monthly_revenue = np.array([100,200,230,102,400,130,400,204,665,384,553,452])
monthly_revenue[0:5]
print(monthly_revenue[0::2])

[100 230 400 400 665 553]


In [8]:
## if step is -1 then it  will reverse
print(monthly_revenue[::-1])

[452 553 384 665 204 400 130 400 102 230 200 100]


### Part4 - Advance slicing
        - Using boolean array for indexing
        - Combining slicing with conditional statement

In [9]:
avg = np.mean(monthly_revenue)
avg

318.3333333333333

In [10]:
monthly_revenue > avg

array([False, False, False, False,  True, False,  True, False,  True,
        True,  True,  True])

In [11]:
monthly_revenue[monthly_revenue > avg]

array([400, 400, 665, 384, 553, 452])

### Part5 - Important Caveats and Best practice

        - Slices are views not copies

### Task 1

In [12]:
monthly_sales = np.array([200,220,250,275,300,320,350,370,400,420,450,475])

In [13]:
# sales of januray and december
print(monthly_sales[0])
print(monthly_sales[-1])

200
475


In [18]:
# Access quatarly data
q1 = monthly_sales[:3]
q2 = monthly_sales[3:6]
q3 = monthly_sales[6:9]
q4 = monthly_sales[9:]
print('First quatar mean: ',q1.mean())
print('Second quatar mean: ',q2.mean())
print('Third quatar mean: ',q3.mean())
print('Forth quatar mean: ',q4.mean())

First quatar mean:  223.33333333333334
Second quatar mean:  298.3333333333333
Third quatar mean:  373.3333333333333
Forth quatar mean:  448.3333333333333


In [19]:
# update april sales to 280
monthly_sales[3] = 280
print(monthly_sales)

[200 220 250 280 300 320 350 370 400 420 450 475]


## Loop vs Vectorization

### basic loop

In [20]:
daily_user = [200,220,250,275]
avg_user = 0

for user in daily_user:
  avg_user += user

print(avg_user/len(daily_user))

236.25


### Inro to Vectorization

In [21]:
du_np = np.array(daily_user)

du_np.mean()

236.25

### Performance comparision

In [26]:
large_array = np.random.randint(1,100,size = 100000000)
large_array

array([52, 49,  7, ..., 66, 80, 88])

In [29]:
import time

st_time = time.time()
avg = 0
for i in large_array:
  avg += i

print(avg/100000000)
ed_time = time.time()
print(ed_time - st_time)

49.99525337
18.425623893737793


In [30]:
star_time = 0
print(np.mean(large_array))
end_time = 0
print(end_time - star_time)

49.99525337
0


### Unniversal function

In [31]:
product_price = np.array([20,24,32,13,25])
np.sqrt(product_price)

array([4.47213595, 4.89897949, 5.65685425, 3.60555128, 5.        ])

        common arithmetic like addition,subtraction,multipication and division

        

In [34]:
revenue = np.array([4000,4500,4200])
expense = np.array([2000,2200,1500])

profit = np.subtract(revenue,expense)
print(profit)
print(np.add(revenue,expense))
print(np.multiply(revenue,expense))
print(np.divide(revenue,expense))

[2000 2300 2700]
[6000 6700 5700]
[8000000 9900000 6300000]
[2.         2.04545455 2.8       ]


        - Trigonometric function: np.sin(), np.cos()
        - Logarothimic fucntion: np.log(),np.exp()

In [36]:
principle = 1000
rate = 0.05

year = np.array([1,2,3,4,5])

compound_interest = np.multiply(principle , np.exp(rate*year))
compound_interest

array([1051.27109638, 1105.17091808, 1161.83424273, 1221.40275816,
       1284.02541669])

## Conditional filtering


In [37]:
## np.where(condition,if true, else)

score = np.array([85,90,91,93])
elegible = np.where(score>85,'A+','Fail')
elegible

array(['Fail', 'A+', 'A+', 'A+'], dtype='<U4')

## Reshaping array

In [38]:
data = np.random.randint(10,100,100)

data.reshape(100,1)

array([[73],
       [53],
       [17],
       [60],
       [93],
       [44],
       [90],
       [64],
       [16],
       [25],
       [66],
       [44],
       [36],
       [21],
       [43],
       [52],
       [72],
       [84],
       [59],
       [77],
       [52],
       [11],
       [71],
       [38],
       [50],
       [74],
       [65],
       [76],
       [82],
       [30],
       [34],
       [42],
       [73],
       [74],
       [15],
       [95],
       [13],
       [18],
       [86],
       [27],
       [44],
       [85],
       [12],
       [39],
       [20],
       [37],
       [19],
       [61],
       [35],
       [14],
       [26],
       [80],
       [73],
       [61],
       [34],
       [73],
       [67],
       [17],
       [95],
       [43],
       [26],
       [96],
       [56],
       [57],
       [62],
       [81],
       [69],
       [82],
       [80],
       [33],
       [34],
       [38],
       [54],
       [88],
       [95],
       [93],
       [31],

In [39]:
# if one dimention is unknown then we can use -1 in that. but only on one dimention
data.reshape(-1,1) # let's first dimention is unknown

array([[73],
       [53],
       [17],
       [60],
       [93],
       [44],
       [90],
       [64],
       [16],
       [25],
       [66],
       [44],
       [36],
       [21],
       [43],
       [52],
       [72],
       [84],
       [59],
       [77],
       [52],
       [11],
       [71],
       [38],
       [50],
       [74],
       [65],
       [76],
       [82],
       [30],
       [34],
       [42],
       [73],
       [74],
       [15],
       [95],
       [13],
       [18],
       [86],
       [27],
       [44],
       [85],
       [12],
       [39],
       [20],
       [37],
       [19],
       [61],
       [35],
       [14],
       [26],
       [80],
       [73],
       [61],
       [34],
       [73],
       [67],
       [17],
       [95],
       [43],
       [26],
       [96],
       [56],
       [57],
       [62],
       [81],
       [69],
       [82],
       [80],
       [33],
       [34],
       [38],
       [54],
       [88],
       [95],
       [93],
       [31],

In [40]:
# reshape show be done as reshape(a,b) that a*b = size of original
data.reshape(50,2)

array([[73, 53],
       [17, 60],
       [93, 44],
       [90, 64],
       [16, 25],
       [66, 44],
       [36, 21],
       [43, 52],
       [72, 84],
       [59, 77],
       [52, 11],
       [71, 38],
       [50, 74],
       [65, 76],
       [82, 30],
       [34, 42],
       [73, 74],
       [15, 95],
       [13, 18],
       [86, 27],
       [44, 85],
       [12, 39],
       [20, 37],
       [19, 61],
       [35, 14],
       [26, 80],
       [73, 61],
       [34, 73],
       [67, 17],
       [95, 43],
       [26, 96],
       [56, 57],
       [62, 81],
       [69, 82],
       [80, 33],
       [34, 38],
       [54, 88],
       [95, 93],
       [31, 73],
       [22, 33],
       [61, 32],
       [46, 69],
       [47, 27],
       [42, 78],
       [34, 59],
       [85, 97],
       [33, 77],
       [53, 75],
       [79, 11],
       [56, 81]])

In [41]:
data.reshape(50,3)

ValueError: cannot reshape array of size 100 into shape (50,3)

## Flattening data

In [42]:
data2 = np.random.randint(10,100,25)
data2 = data2.reshape(5,5)

In [43]:
data2

array([[67, 40, 92, 38, 30],
       [17, 43, 32, 10, 20],
       [49, 56, 69, 47, 62],
       [78, 18, 86, 45, 94],
       [61, 16, 89, 66, 31]])

In [46]:
# Now to flatten the array we can use flatten() or ravel() function.
# flatten() return a copy of original array
# but ravel() return the original array

data3 = data2.flatten()
data3[0] = 100
print(data2)
print(data3)

[[67 40 92 38 30]
 [17 43 32 10 20]
 [49 56 69 47 62]
 [78 18 86 45 94]
 [61 16 89 66 31]]
[100  40  92  38  30  17  43  32  10  20  49  56  69  47  62  78  18  86
  45  94  61  16  89  66  31]


In [47]:
# using ravel() will reference the original array so changing in new array change the original
data4 = data2.ravel()
data4[0] = 100
print(data2)
print(data4)

[[100  40  92  38  30]
 [ 17  43  32  10  20]
 [ 49  56  69  47  62]
 [ 78  18  86  45  94]
 [ 61  16  89  66  31]]
[100  40  92  38  30  17  43  32  10  20  49  56  69  47  62  78  18  86
  45  94  61  16  89  66  31]


## Transposing array

In [48]:
data_T = np.random.randint(10,100,20).reshape(2,10)
print(data_T)
print(data_T.T)

[[60 59 44 49 22 57 56 92 13 14]
 [14 66 84 14 95 71 30 13 66 58]]
[[60 14]
 [59 66]
 [44 84]
 [49 14]
 [22 95]
 [57 71]
 [56 30]
 [92 13]
 [13 66]
 [14 58]]


### Resize array


In [49]:
np.resize(data_T,(4,5))

array([[60, 59, 44, 49, 22],
       [57, 56, 92, 13, 14],
       [14, 66, 84, 14, 95],
       [71, 30, 13, 66, 58]])

## Handling missing data

### Understanding missing data
        - Types of missing values: completely missing, partially missing and incorrectly entered
        - common reasons for missing data: data entry error, unavailablity of informatin etc.

In [50]:
customer_data = np.array([100,230,301,134,np.nan,302,443])
print(customer_data.max()) # it will print nan but it is not true so we have handle missing data

nan


### identify missing data using np.isnan()

In [52]:
missing_value = np.isnan(customer_data)

In [53]:
print("Number of misssing values: ",np.sum(missing_value))

Number of misssing values:  1


### Replacing missing values

In [54]:
np.nan_to_num(customer_data) # it will replace nan to 0

array([100., 230., 301., 134.,   0., 302., 443.])

In [56]:
# filling with mean() or median()
np.nanmean(customer_data)
customer_data

array([100., 230., 301., 134.,  nan, 302., 443.])

In [57]:
# it does not fill autometically so we should do it manually
data_fill = np.where(np.isnan(customer_data),np.nanmean(customer_data),customer_data)
data_fill

array([100.        , 230.        , 301.        , 134.        ,
       251.66666667, 302.        , 443.        ])

### deleting the missing data

In [58]:
data_without_nan = customer_data[~np.isnan(customer_data)]
data_without_nan

array([100., 230., 301., 134., 302., 443.])

### forward and backward filling of missing data
      using methods to fill missing data based on neighbours element

In [59]:
copy_cd = np.copy(customer_data)
mask = np.isnan(copy_cd)

copy_cd[mask] = np.roll(copy_cd,shift=-1)[mask]
copy_cd

array([100., 230., 301., 134., 302., 302., 443.])

### File Handleing -- Saving and Loading Numpy array

In [60]:
age = np.array([23,45,32,53,43])
np.save('age.npy',age)

### Load the saving file

In [62]:
load_age = np.load('age.npy')
load_age

array([23, 45, 32, 53, 43])

### Save text

In [63]:
np.savetxt('age.txt',load_age,delimiter=',')

### Load text

In [64]:
new_age = np.loadtxt('age.txt',delimiter=',')
new_age

array([23., 45., 32., 53., 43.])